### ISSUE TITLE
완성된 크롤러의 데이터베이스를 DRF와 연동

### ISSUE THREAD

**Issue by froggy-hyun** [osamhack2022/WEB_APP_Goondae-goonde_Open-mind#10]
Crawler DB 를 Django Multiple DB로 연결 및 라우터 설정

**Comment by SolfE** [comment]
방법이 2가지가 있습니다.

1. Clawler Data를 DRF DB에 직접 저장하는 방법
**2. Clawler Data를 data.db파일에 별도로 저장하여 DRF로 연동하는 방법**

원활한 협업을 위하여 Clawer를 헤치지 않는 2번 방법으로 진행하겠습니다.

**Comment by SolfE** [comment]
#33

**Comment by SolfE** [comment]
#33
