### ISSUE TITLE
location 모델에 likes 구현

### ISSUE THREAD

**Issue by froggy-hyun** [osamhack2022/WEB_APP_Goondae-goonde_Open-mind#100]

**Comment by froggy-hyun** [comment]
현재 loaction 모델은 크롤링해서 오는거라 likes 항목을 추가하면 'no such table: crawled_data_likes' 에러가 뜹니다. 이를 해결해보려 db생성시 likes TEXT(db에는 리스트 항목이 없기 때문에 문자열 속성으로 정의)항목을 만들고 빈값을 넣은 후 likes 항목에 있는 값을 가져올때 리스트로 변환하는 아이디어를 적용해 보았지만 구현 실패하였습니다.

**Comment by SolfE** [comment]
현 버전에서는 해결된 이슈라 내려주셔도 될거 같습니다!
