### ISSUE TITLE
회원가입시 이메일 확인 알림 페이지로 리다이렉트 되도록 구현

### ISSUE THREAD

**Issue by froggy-hyun** [osamhack2022/WEB_APP_Goondae-goonde_Open-mind#104]
현재 회원가입시 이메일을 확인하세요 라고 뜨는데 이메일 확인 페이지로 보여주는것이 좋을거 같습니다. ex)회원가입이 완료되었습니다. 이메일 인증을 진행해 주세요.

**Comment by in-woong** [comment]
문구를 회원가입이 완료되었습니다. 이메일 인증을 진행해 주세요
로 바꾸면 된다는 것인가요? 아니면 링크를 걸어달라는 말씀이신가요??

**Comment by froggy-hyun** [comment]
> 문구를 회원가입이 완료되었습니다. 이메일 인증을 진행해 주세요 로 바꾸면 된다는 것인가요? 아니면 링크를 걸어달라는 말씀이신가요??

회원가입이 완료되었다는 화면으로 넘어가게 하거나 불가능하시다면 문구를 바꿔주시면 될거 같습니다

**Comment by in-woong** [comment]
회원가입이 완료되었습니다. 이메일을 확인해주세요 라고 되어있는 페이지로 넘어가도록 변경하겠습니다.
