### ISSUE TITLE
크롤러 12~15번 항목 크롤링시 오류

### ISSUE THREAD

**Issue by froggy-hyun** [osamhack2022/WEB_APP_Goondae-goonde_Open-mind#105]
12. pocheonsi
13. changwonsi
14. nonsansi
15. yeongcheonsi

위 지역들 크롤링시 크롤링 오류 발생합니다.

**Comment by KimPalZa** [comment]
클롤러 12~15항목은 공공데이터 포탈 api에서 데이터를 가져옵니다. 따라서 발급받은 api가 필요합니다. 발급받은 api 키를 '*'처리된 부분에 입력하지면 작동합니다.
