### ISSUE TITLE
육군 장병을 위한 api 추가

### ISSUE THREAD

**Issue by froggy-hyun** [osamhack2022/WEB_APP_Goondae-goonde_Open-mind#108]
국방부_육군 장병 확인 : https://www.data.go.kr/data/15106254/openapi.do
국방부_육군 장병 휴가 내역 조회 : https://www.data.go.kr/data/15106273/openapi.do

**Comment by in-woong** [comment]
어떻게 사용을 원하시는 건가요?? @froggy-hyun

**Comment by froggy-hyun** [comment]
> 어떻게 사용을 원하시는 건가요?? @froggy-hyun 

단순히 육군소속인증정보와 휴가내역을 보여주어 휴가나온장병이라는것을 업소이용시 보여줄 수 있도록만 구현을 원했지만 api사용 신청을 한지 3주가 지났는데 답변이 없어서 사용 못할거 같습니다
