### ISSUE TITLE
Location 카테고리 검색 추가

### ISSUE THREAD

**Issue by SolfE** [osamhack2022/WEB_APP_Goondae-goonde_Open-mind#41]
- [x] 1. 페이징 한 페이지당 3개씩 보여주던 방식에서 8개로 변경
- [x] 2. 카테고리 파라미터로 Location 분류 조회 기능 제작

**Comment by in-woong** [comment]
변경 완료되면, index 페이지 category 별로 나올 수 있도록 수정하겠습니다.

**Comment by SolfE** [comment]
페이징 한 페이지당 8개화 완료

**Comment by SolfE** [comment]
@in-woong  
혹시 page파라미터를 변경하시려는 이유랑 원하시는 URL구조가 있으신가요??
어떤 식으로 변경해야할지 감이 안잡혀서 일단 보류하고 있습니다!

**Comment by in-woong** [comment]
파라미터에 카테고리를 추가하면 좋겠다는 의견이었습니다!

**Comment by SolfE** [comment]
@in-woong
확인했습니다! 아래와 같은 형태로 URL 파라미터를 받게 구현하겠습니다.
`/locations/?category={카테고리명}`
