### ISSUE TITLE
의정부시 크롤링시 오류

### ISSUE THREAD

**Issue by froggy-hyun** [osamhack2022/WEB_APP_Goondae-goonde_Open-mind#46]
![캡처](https://user-images.githubusercontent.com/111727754/194806572-db0db92a-7a5a-4009-80c1-0b2d0ee15a2e.PNG)

**Comment by froggy-hyun** [comment]
8. MOUdata 또한 동일
![캡처](https://user-images.githubusercontent.com/111727754/194806779-721d22c4-a112-461b-8c3b-1150d063583d.PNG)

**Comment by KimPalZa** [comment]
의정부시 크롤링 같은 경우 제 개발환경에서 정상 작동하고 있습니다. 크롤러를 만들면서 requests를 통해 서버 측에 HTML을 요청해서 가져오고 있는데 이거 자체가 서버에 부하를 주는 거라... 만약 서버에서 지정한 횟수를 초과한 경우 요청이 차단되는 경우가 종종 있었고, 시간이 지나면 저절로 해결 되었습니다.
IP을 바꿔서 요청하거나 암호화하는 방법도 있지만, 저희가 수집하는 데이터 자체가 업데이트가 자주 되지 않아서 그냥 시간이 지난 뒤 다시 요청하는 방법이 좋을 거 같습니다!

MOU 데이터 같은 경우 국방부 공공데이터 API를 통해 가져오고 있습니다. 원격저장소에 API key를 그대로 저장하는 것은 좋지 않을 거 같아서 해당 부분을 '*'로 바꿔서 표시했습니다.

**Comment by froggy-hyun** [comment]
네 알겠습니다 !
