### ISSUE TITLE
크롤러 완성하기

### ISSUE THREAD

**Issue by froggy-hyun** [osamhack2022/WEB_APP_Goondae-goonde_Open-mind#7]

**Comment by KimPalZa** [comment]
**크롤러 구현**
 지역 웹사이트 및 공공데이터api에 공개되어 있는 군 우대업소 정보를 그대로 크롤링하여 다음과 같은 내용을 담은 리스트로 반환
- 업소명(name)
- 업종(category)
- 주소(address)
- 전화번호(number)
- 혜택(benefit)

**크롤러 개선사항(Todo)**
1. 크롤러 모듈화
2. 크롤링 된 데이터 다듬기(주소 표준화, 업종 통일)
3. 처리할 수 있는 오류 예외처리(인증서 문제의 경우 오류 warning 메시지가 뜨지만 크롤러 정상작동, 웹사이트에서 허용한 크롤링 횟수를 초과한 경우 등)
4. 크롤러 속도 및 성능개선(병렬처리, 너무 정적인 부분 개선하여 웹사이트 변화에 대응)

**Comment by SolfE** [comment]
백엔드 웹프레임워크의 기능적인 한계로 DB를 통일하여 사용하겠습니다!
