### ISSUE TITLE
배포를 위한 서버환경 구축

### ISSUE THREAD

**Issue by SolfE** [osamhack2022/WEB_APP_Goondae-goonde_Open-mind#72]
AWS를 위한 배포 환경 구축

**Comment by in-woong** [comment]
혹시 Docker나 AWS 환경 구축 하시는데 어려움 있으시면 말씀해주세요 어느정도 할 줄 알고 있습니다.

**Comment by SolfE** [comment]
http://ec2-52-79-185-182.ap-northeast-2.compute.amazonaws.com:3000/ AWS 1차 배포완료
