### ISSUE TITLE
review 구현 변화가 필요

### ISSUE THREAD

**Issue by froggy-hyun** [osamhack2022/WEB_APP_Goondae-goonde_Open-mind#89]
현재 review 기능이 post을 참고한 방식인데 방식을 참고하는것 보다 모델은 post모델을 참고하되 시리얼라이저에서 class Location 에 reviews = ReviewSerializer를 추가하는 방식을 선택해야 댓글 처럼 구현 가능함

**Comment by SolfE** [comment]
@froggy-hyun 님 이거 직접 구현하시나요?
