### ISSUE TITLE
Review모델에 좋아요를 likes(좋아요수)와 likers(좋아요누른사람)으로 세분화하기

### ISSUE THREAD

**Issue by froggy-hyun** [osamhack2022/WEB_APP_Goondae-goonde_Open-mind#95]
Review모델에 좋아요를 likes(좋아요수)와 likers(좋아요누른사람)으로 세분화하기

**Comment by SolfE** [comment]
#102 에서 작업 완료하였습니다.
1. review list, detail 에서 total_like 조회가능
